Repository FRONTENDSCHOOL8/shoong, pull requests merged in 2024-04, with the labels that each got.

#115 [Feat] 소셜로그인 구현 (카카오) 및 회원가입 Button 감싸고 있던 Link 태그 삭제
  src/components/ExchangeList/ExchangeList.jsx
  src/main.jsx
  src/pages/Login/InstaLogin.jsx
  src/pages/Login/InstaRedirect.jsx
  src/pages/Login/KakaoLogin.jsx
  src/pages/Login/KakaoRedirect.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/NaverLogin.jsx
  src/pages/Login/NaverRedirect.jsx
  src/pages/Register/Register.jsx
Labels: feature

#117 [Feat] 모달 컴포넌트 수정, 포토카드 제보하기 페이지 구현
  src/Layout/Header/Header.jsx
  src/components/ConfirmationModal/ConfirmationModal.jsx
  src/components/MyBias/MyBias.jsx
  src/loader/usePhocaData.js
  src/main.jsx
  src/pages/InformUs/InformUs.jsx
  src/pages/Login/NaverRedirect.jsx
  src/pages/MeetUpSubmit/MeetUpSubmit.jsx
  src/pages/MyBias/MyBias.jsx
  src/pages/PhotoCardSubmit/PhotoCardSubmit.jsx
  src/pages/Profile/Profile.jsx
  src/styles/tailwind.css
Labels: feature

#121 [Modify] 서치바 기능 업데이트
  src/components/PhocaContainer/PhocaContainerEx.jsx
  src/components/SearchBar/SearchBar.jsx
  src/store/store.js
Labels: feature

#122 [Feat] 회원가입 페이지 - Validation 기능 구현 / DatePicker 컴포넌트 추가 / 이메일 인증 구현
  package.json
  pnpm-lock.yaml
  src/components/Button/Button.jsx
  src/components/Input/Input.jsx
  src/pages/Login/Login.jsx
  src/pages/Register/Register.jsx
  src/pages/Register/RegularExpressions.jsx
  src/pages/Register/TermsCheckbox.jsx
  src/pages/Register/Twilio.jsx
  src/pages/Register/useCheckbox.jsx
  src/pages/Register/useSubmit.jsx
  src/pages/Register/useValidation.jsx
  src/pages/Register/useVerified.jsx
  src/styles/Mui.css
  src/styles/tailwind.css
Labels: feature

#123 [Modify] DetailHeader 컴포넌트의 뒤로가기 화살표에 키보드 포커스 추가
  src/components/DetailHeader/DetailHeader.jsx
Labels: enhancement

#128 [Feat] 회원가입 페이지 모바일 버전 기초공사
  pnpm-lock.yaml
  src/pages/Register/Register.jsx
  src/pages/Register/RegisterMobile.jsx
  src/pages/Register/useCheckbox.jsx
  src/pages/Register/useSubmit.jsx
  src/pages/Register/useValidation.jsx
Labels: enhancement

#129 [Modify] 스와이퍼 라이브러리 교체
  package.json
  pnpm-lock.yaml
  src/components/Carousel/ MeetupCarousel.jsx
  src/components/Carousel/Carousel.jsx
  src/components/Carousel/Slides.jsx
  src/components/Carousel/VerticalCarousel.jsx
  src/components/Carousel/slick-theme.css
  src/main.jsx
  src/pages/Home/Home.jsx
Labels: enhancement

#131 [Feat] 제보하기 페이지 기능 구현 및 리팩토링, 모달 컴포넌트 마크업 및 스타일링 변경, 교환 페이지 레이아웃 변경
  index.html
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/components/BiasContainer/BiasContainer.jsx
  src/components/ConfirmationModal/ConfirmationModal.jsx
  src/components/Dropdown/Dropdown.jsx
  src/components/GroupSelector/GroupSelector.jsx
  src/components/ImageUploader/ImageUploader.jsx
  src/components/PhocaContainer/PhocaContainerBias.jsx
  src/components/PhocaContainer/PhocaContainerEx.jsx
  src/components/PhocaContainer/Responsive.css
  src/components/PhocaItem/ArtistInfo.jsx
  src/components/PhocaItem/ArtistLogo.jsx
  src/components/PhocaItem/PhocaImg.jsx
  src/components/PhocaItem/PhocaLikeCount.jsx
  src/components/PhocaItem/PhocaTitle.jsx
  src/components/SearchBar/SearchBar.jsx
  src/data/data.json
  src/main.jsx
  src/pages/Exchange/Exchange.jsx
  src/pages/Home/Home.jsx
  src/pages/InformUs/InformUs.jsx
  src/pages/MeetUpSubmit/MeetUpSubmit.jsx
  src/pages/MeetUpSubmit/useAddressSearch.js
  src/pages/MyBias/MyBias.jsx
  src/pages/PhotoCardSubmit/PhotoCardSubmit.jsx
  src/pages/ProfileSetting/LoginInfo.jsx
  src/styles/tailwind.css
  tailwind.config.js
Labels: enhancement, feature

#134 [Feat] desktopHeader 구현
  src/Layout/Header/DesktopHeader.jsx
  src/Layout/Header/Header.jsx
  src/Layout/RootLayout/RootLayout.jsx
  src/components/Carousel/VerticalCarousel.jsx
  src/pages/Home/Home.jsx
Labels: feature
