Repository FRONTENDSCHOOL8/shoong, pull requests merged in 2024-03, with the labels that each got.

#18 [Feat] SortingBar컴포넌트
  package.json
  pnpm-lock.yaml
  src/components/SortingBar/SortingBar.jsx
  src/components/SortingBar/SortingBar.stories.jsx
  src/loader/index.js
  src/loader/phocaData.js
  src/main.jsx
  src/store/store.js
  src/styles/App.css
Labels: feature

#22 [Feat] PhocaItem 컴포넌트 #19
  public/blackpink.jpeg
  public/phoca.jpeg
  src/components/PhocaContainer/PhocaContainer.jsx
  src/components/PhocaContainer/PhocaContainer.stories.jsx
  src/components/PhocaItem/ArtistInfo.jsx
  src/components/PhocaItem/ArtistLogo.jsx
  src/components/PhocaItem/PhocaImg.jsx
  src/components/PhocaItem/PhocaItem.jsx
  src/components/PhocaItem/PhocaItem.stories.jsx
  src/components/PhocaItem/PhocaLikeButton.jsx
  src/components/PhocaItem/PhocaLikeCount.jsx
  src/components/PhocaItem/PhocaTitle.jsx
  src/main.jsx
  src/pages/ExchangeDetail/ExchangeDetail.jsx
  src/pages/Home/Home.jsx
Labels: feature

#24 Feat/floating button , useProfileImage 작성
  public/icons/floatingDefault.jpg
  src/components/FloatingButton/FloatingButton.jsx
  src/components/FloatingButton/FloatingButton.stories.jsx
  src/components/FloatingButton/useProfileImage.js
  src/main.jsx
  src/pages/Home/Home.jsx
Labels: feature

#27 [Feat] PhocaItem 컴포넌트 수정 #26
  .prettierrc.cjs
  package.json
  pnpm-lock.yaml
  src/components/PhocaItem/ArtistInfo.jsx
  src/components/PhocaItem/PhocaImg.jsx
  src/components/PhocaItem/PhocaItem.jsx
  src/components/PhocaItem/PhocaTitle.jsx
Labels: enhancement

#29 [2주차] Bias, BiasContainer 컴포넌트
  .prettierrc.cjs
  src/components/Bias/Bias.jsx
  src/components/BiasContainer/BiasContainer.jsx
  src/store/store.js
Labels: enhancement

#31 [Feat]search bar 구현
  src/components/SearchBar/SearchBar.jsx
  src/pages/Exchange/Exchange.jsx
  src/pages/MeetUp/MeetUps.jsx
  src/store/store.js
Labels: feature

#35 Feat/profile header
  src/components/ProfileTitle/ProfileHeader.jsx
  src/components/ProfileTitle/ProfileInfo.jsx
  src/components/ProfileTitle/ProfileTitle.jsx
  src/loader/index.js
  src/loader/userData.js
  src/main.jsx
  src/pages/Profile/Profile.jsx
Labels: feature

#37 [Feat] DetailHeader 컴포넌트, BottomSheet 컴포넌트, useBottomSheet 커스텀 훅 완성
  public/radioChecked.svg
  public/radioUnchecked.svg
  src/components/BottomSheet/BottomSheet.jsx
  src/components/BottomSheet/useBottomSheet.jsx
  src/components/Button/Button.jsx
  src/components/DetailHeader/DetailHeader.jsx
Labels: feature

#40 [Modify] BottomSheet 컴포넌트에 들어가는 라디오버튼 스타일링을 위한 이미지 경로를 절대경로로 수정!
  src/components/BottomSheet/BottomSheet.jsx
Labels: enhancement

#39 [Modify] Header에 들어가는 로고의 경로를 절대경로로 수정
  src/Layout/Header/Header.jsx
Labels: enhancement

#42 [Modify] Header 컴포넌트 스타일링 조정
  src/Layout/Header/Header.jsx
Labels: enhancement

#44 [Modify] 플로팅버튼css수정, 메인카드컨테이너 적용
  src/components/FloatingButton/FloatingButton.jsx
  src/pages/Home/Home.jsx
Labels: enhancement, feature

#46 [Feat] CollectBookDetail 컴포넌트
  package.json
  pnpm-lock.yaml
  src/components/CollectBook/CollectBook.jsx
  src/components/CollectBookItem/CollectBookItem.jsx
  src/components/CollectBookItemContainer/CollectBookItemContainer.jsx
  src/components/DragonSphere/DragonSphere.jsx
  src/components/ProfileItemContainer/ProfileItemContainer.jsx
  src/components/ToastAlert/ToastAlert.jsx
  src/components/ToastButton/ToastButton.jsx
  src/main.jsx
  src/pages/CollectBook/CollectBook.jsx
  src/pages/ColloectBookDetail/ColloectBookDetail.jsx
Labels: enhancement, feature

#48 [Feat] CollectBookDetail 페이지 삭제 기능
  public/icons/드래곤볼.jpg
  src/components/CollectBook/CollectBook.jsx
  src/components/CollectBookItemContainer/CollectBookItemContainer.jsx
  src/components/DragonSphere/DragonSphere.jsx
  src/components/ToastAlert/ToastAlert.jsx
  src/components/ToastButton/ToastButton.jsx
  src/pages/ColloectBookDetail/ColloectBookDetail.jsx
  src/pages/Profile/Profile.jsx
Labels: enhancement, feature

#57 [Feat] carousel 구현
  package.json
  pnpm-lock.yaml
  public/carousel/carousel_1.jpeg
  public/carousel/carousel_2.jpeg
  public/carousel/carousel_3.jpeg
  public/carousel/carousel_4.jpeg
  src/components/Carousel/Carousel.jsx
  src/components/Carousel/Slides.jsx
  src/components/Carousel/VerticalCarousel.jsx
  src/components/SearchBar/SearchBar.jsx
  src/pages/Home/Home.jsx
Labels: feature

#59 Feature/detail header
  src/components/BottomSheet/BottomSheet.jsx
  src/components/BottomSheet/BottomSheetAnimation.jsx
  src/components/BottomSheet/BottomSheetAnimation2.jsx
  src/components/BottomSheet/BottomSheetLayout.jsx
  src/components/BottomSheet/useBottomSheet.jsx
  src/components/DetailHeader/DetailHeader.jsx
Labels: enhancement

#61 [Feat] 이미지 배너 및 Home 페이지 레이아웃 조정
  public/banner_1.png
  public/banner_faq.png
  src/components/Carousel/VerticalCarousel.jsx
  src/components/FloatingButton/FloatingButton.jsx
  src/components/ImageLink/ImageLink.jsx
  src/components/MainCardContainer/MainCardContainer.jsx
  src/pages/Home/Home.jsx
Labels: enhancement, feature

#63 [Feat] Header 컴포넌트 fixed 설정
  src/Layout/Header/Header.jsx
Labels: enhancement

#64 [Modify] DetailHeader 컴포넌트 수정
  src/components/DetailHeader/DetailHeader.jsx
Labels: enhancement

#68 [Feat] Footer, ProfileSetting, MyBias 컴포넌트
  public/myBias.jpg
  src/Layout/Footer/Footer.jsx
  src/assets/icons/myBias.svg
  src/components/Bias/Bias.jsx
  src/components/MyBias/MyBias.jsx
  src/components/NavigationTile/NavigationTile.jsx
  src/components/PhocaContainer/PhocaContainerEx.jsx
  src/components/PhocaItem/PhocaItem.jsx
  src/components/PhocaItem/PhocaLikeButton.jsx
  src/components/PhocaItem/PhocaTitle.jsx
  src/components/PhocaItem/updateUserLikeList.js
  src/components/PhocaItem/userData.js
  src/components/ProfileFooter/ProfileFooter.jsx
  src/components/ProfileTitle/ProfileInfo.jsx
  src/components/ProfileTitle/ProfileTitle.jsx
  src/loader/usePhocaData.js
  src/main.jsx
  src/pages/Home/Home.jsx
  src/pages/MyBias/MyBias.jsx
  src/pages/Profile/Profile.jsx
  src/pages/ProfileSetting/LoginInfo.jsx
  src/pages/ProfileSetting/ProfileSetting.jsx
  src/store/store.js
Labels: feature

#72 [Feat] 콜렉트북 페이지 디자인 수정
  src/components/CollectBook/CollectBook.jsx
  src/components/CollectBookItem/CollectBookItem.jsx
  src/components/CollectBookItemContainer/CollectBookItemContainer.jsx
  src/components/DragonSphere/DragonSphere.jsx
  src/components/ProfileItemContainer/ProfileItemContainer.jsx
  src/components/ToggleButton/ToggleButton.jsx
  src/pages/ColloectBookDetail/ColloectBookDetail.jsx
Labels: enhancement

#74 [Feat] 로그인 페이지 구현 중간 공유
  public/checkboxChecked.svg
  public/checkboxUnchecked.svg
  public/icons/instagram.svg
  public/icons/kakao.svg
  public/icons/naver.svg
  public/icons/shoongLogoLogin.svg
  src/Layout/RootLayout/RootLayout.jsx
  src/components/Button/Button.jsx
  src/components/Input/Input.jsx
  src/pages/Login/Login.jsx
  src/pages/Register/Register.jsx
Labels: feature

#76 [Feat] 교환 페이지 바텀시트 추가, 레이아웃 변경
  src/components/BiasContainer/BiasContainer.jsx
  src/components/BottomSheet/BottomSheet.jsx
  src/components/BottomSheet/BottomSheetLayout.jsx
  src/components/PhocaContainer/PhocaContainerEx.jsx
  src/components/SortingBar/SortingBar.jsx
  src/pages/Exchange/Exchange.jsx
  src/store/store.js
Labels: enhancement, feature

#78 [Feat] 로그인 관련 기능
  src/Layout/NavBar/NavBar.jsx
  src/components/CollectBook/CollectBook.jsx
  src/components/ProfileItemContainer/ProfileItemContainer.jsx
  src/main.jsx
  src/pages/ColloectBookDetail/ColloectBookDetail.jsx
  src/pages/Login/Login.jsx
  src/pages/NotFound/NotFound.jsx
  src/store/store.js
Labels: enhancement, feature

#83 [Feat]
  src/components/Comment/CommentContainer.jsx
  src/components/Comment/CommentInput.jsx
  src/components/Comment/CommentItem.jsx
  src/components/FloatingButton/useProfileImage.js
  src/components/MeetUpDetail/MeetUpDetail.jsx
  src/store/store.js
Labels: feature

#92 [Feat]
  src/components/Carousel/VerticalCarousel.jsx
  src/components/Comment/CommentInput.jsx
  src/components/FloatingButton/FloatingButton.jsx
  src/components/FloatingButton/useProfileImage.js
  src/components/ImageLink/ImageLink.jsx
  src/components/MainCardContainer/MainCardContainer.jsx
  src/components/ProfileTitle/ProfileInfo.jsx
  src/pages/Home/Home.jsx
  src/styles/App.css
Labels: feature

#94 [Modify] 교환글에서 유저의 id를 동적으로 데이터 받아와서 렌더링
  index.html
  src/components/BottomSheet/BottomSheet.jsx
  src/components/Carousel/VerticalCarousel.jsx
  src/components/ExchangeList/ExchangeList.jsx
  src/components/ExchangeListDetail/ExchangeArticle.jsx
  src/components/ExchangeListDetail/ExchangeEdit.jsx
  src/components/MeetUpDetail/MeetUpDetail.jsx
  src/components/MeetUpMap/MeetUpMap.jsx
  src/font/SUIT-Variable.woff2
  src/main.jsx
  src/pages/ExchangeDetail/ExchangeDetail.jsx
  src/pages/MeetUp/MeetUp.jsx
  src/styles/tailwind.css
  tailwind.config.js
  vite.config.js
Labels: bug, enhancement

#95 [Feat] 스크롤 상단 고정 컴포넌트 추가
  src/Layout/RootLayout/RootLayout.jsx
  src/Layout/ScrollToTop/ScrollToTop.jsx
Labels: feature

#100 [Modify] commentInput 버그 수정
  src/components/Comment/CommentInput.jsx
  src/components/DetailHeader/DetailHeader.jsx
Labels: bug

#105 [Feat] 회원가입 페이지 절반의 완성 (+발표를 위한 console.log 제거, LikeDetail 페이지 header 제거)
  src/Layout/Header/Header.jsx
  src/components/BottomSheet/BottomSheetAnimation2.jsx
  src/components/Button/Button.jsx
  src/components/Carousel/VerticalCarousel.jsx
  src/components/Comment/CommentInput.jsx
  src/components/ExchangeList/ExchangeList.jsx
  src/components/ExchangeListDetail/ExchangeArticle.jsx
  src/components/ExchangeListDetail/ExchangeEdit.jsx
  src/components/Input/Input.jsx
  src/components/PhocaItem/PhocaLikeButton.jsx
  src/components/PhocaItem/updateUserLikeList.js
  src/components/SearchBar/SearchBar.jsx
  src/loader/exchangeDetailData.js
  src/loader/userData.js
  src/main.jsx
  src/pages/LikeDetail/LikeDetail.jsx
  src/pages/ProfileSetting/LoginInfo.jsx
  src/pages/Register/Register.jsx
  src/utils/debounce.js
  src/utils/getNickname.js
Labels: enhancement, feature

#109 [Feat] 이미지 링크 배너 반응형 구현 및 찜목록 링크 연결
  public/banner_11.png
  public/banner_2.png
  public/banner_4.png
  public/banner_5.png
  public/banner_6.png
  public/banner_7.png
  public/carousel/_carousel_4.jpeg
  public/carousel/carousel__1.jpeg
  public/carousel/carousel__2.jpeg
  public/carousel/carousel__3.jpeg
  src/components/Carousel/Carousel.jsx
  src/components/ImageLink/ImageLink.jsx
  src/pages/Exchange/Exchange.jsx
  src/pages/Home/Home.jsx
  src/pages/ProfileSetting/ProfileSetting.jsx
Labels: enhancement

#111 [Modify] 모달창 컴포넌트화, 최애선택 데이터베이스 연동, 푸터 변경
  public/banner_1.png
  public/blackpink.jpeg
  public/phoca.jpeg
  src/Layout/Footer/Footer.jsx
  src/components/ConfirmationModal/ConfirmationModal.jsx
  src/components/ImageLink/ImageLink.jsx
  src/components/PhocaContainer/PhocaContainer.jsx
  src/components/PhocaItem/PhocaItem.jsx
  src/components/PhocaItem/PhocaLikeButton.jsx
  src/pages/MyBias/MyBias.jsx
  src/pages/ProfileSetting/LoginInfo.jsx
Labels: enhancement

#113 [Modify]
  src/components/ConfirmationModal/ConfirmationModal.jsx
  src/components/MyBias/MyBias.jsx
  src/components/PhocaContainer/PhocaContainerBias.jsx
  src/components/PhocaContainer/PhocaContainerEx.jsx
  src/components/PhocaItem/PhocaItem.jsx
  src/components/PhocaItem/PhocaLikeButton.jsx
  src/pages/ProfileSetting/LoginInfo.jsx
  src/styles/App.css
Labels: enhancement

#114 밋업에 검색기능 추가
  src/components/MeetUpItem/MeetUpItem.jsx
  src/components/MeetUpItemContainer/MeetUpItemContainer.jsx
  src/components/PhocaContainer/PhocaContainerEx.jsx
  src/components/SearchBar/SearchBar.jsx
  src/pages/MeetUp/MeetUp.jsx
Labels: feature
